"""Monorepo regression tests.

These exercise real git repositories (rather than mocked subprocess calls)
because the behaviours under test -- consolidation across subdirectories,
nested repository boundaries and linked worktrees -- are defined by actual
git semantics.
"""

import os
import subprocess
from pathlib import Path

import pytest

from ewasd.core import GITIGNORE_FILENAME, Repo


@pytest.fixture(autouse=True)
def hermetic_git(monkeypatch):
    """Isolate tests from the developer's global/system git config."""
    monkeypatch.setenv("GIT_CONFIG_GLOBAL", os.devnull)
    monkeypatch.setenv("GIT_CONFIG_SYSTEM", os.devnull)
    monkeypatch.setenv("GIT_AUTHOR_NAME", "ewasd tests")
    monkeypatch.setenv("GIT_AUTHOR_EMAIL", "tests@example.com")
    monkeypatch.setenv("GIT_COMMITTER_NAME", "ewasd tests")
    monkeypatch.setenv("GIT_COMMITTER_EMAIL", "tests@example.com")


def git(cwd: Path, *args: str) -> str:
    """Run a git command in *cwd* and return stripped stdout."""
    return subprocess.run(
        ["git", *args], cwd=str(cwd), check=True, capture_output=True, text=True
    ).stdout.strip()


def init_repo(path: Path) -> Path:
    """Create a git repo with one empty commit so worktrees can be added."""
    path.mkdir(parents=True, exist_ok=True)
    git(path, "init", "-q", "-b", "main")
    git(path, "commit", "-q", "--allow-empty", "-m", "init")
    return path


def make_link_dir(path: Path, *filenames: str) -> Path:
    """Create a workspace link_dir populated with the given files."""
    path.mkdir(parents=True, exist_ok=True)
    for name in filenames:
        f = path / name
        f.parent.mkdir(parents=True, exist_ok=True)
        f.write_text(f"contents of {name}\n")
    return path


def untracked(repo: Path) -> list[str]:
    """Return untracked paths git reports, honouring the configured excludes."""
    out = git(repo, "status", "--porcelain", "--untracked-files=normal")
    return [line[3:] for line in out.splitlines() if line.startswith("??")]


def excludes_file(repo: Path) -> str:
    """core.excludesFile as seen from *repo* (ewasd stores a resolved path)."""
    return git(repo, "config", "core.excludesFile")


def expected_excludes(repo: Path) -> str:
    """Resolved path so comparisons hold where /tmp is a symlink (macOS, Nix)."""
    return str((repo / GITIGNORE_FILENAME).resolve())


def test_root_operation_preserves_subdir_entries(tmp_path: Path):
    """A root-level ewasd run must not drop entries from subdirectory projects.

    Regression: update_gitignore only consolidated when cwd != git root, so an
    operation at the root replaced the consolidated file with a root-only one.
    Every subdirectory symlink then became untracked again.
    """
    mono = init_repo(tmp_path / "mono")
    subdir = mono / "projects" / "sub"
    subdir.mkdir(parents=True)

    root_repo = Repo("mono", "url", make_link_dir(tmp_path / "ws" / "mono", "ROOT.md"))
    sub_repo = Repo("sub", "url", make_link_dir(tmp_path / "ws" / "sub", "SUB.md"))

    # First link into the subdirectory, then run again at the repo root.
    sub_repo.link_all(subdir)
    root_repo.link_all(mono)

    consolidated = (mono / GITIGNORE_FILENAME).read_text()
    assert "ROOT.md" in consolidated
    assert "projects/sub/SUB.md" in consolidated, (
        "root-level run dropped the subdirectory project's entries"
    )
    assert untracked(mono) == []


def test_root_operation_is_idempotent(tmp_path: Path):
    """Repeated root-level runs must not accumulate or lose entries."""
    mono = init_repo(tmp_path / "mono")
    subdir = mono / "projects" / "sub"
    subdir.mkdir(parents=True)

    root_repo = Repo("mono", "url", make_link_dir(tmp_path / "ws" / "mono", "ROOT.md"))
    sub_repo = Repo("sub", "url", make_link_dir(tmp_path / "ws" / "sub", "SUB.md"))

    sub_repo.link_all(subdir)
    root_repo.link_all(mono)
    first = (mono / GITIGNORE_FILENAME).read_text()
    root_repo.link_all(mono)
    assert (mono / GITIGNORE_FILENAME).read_text() == first
    assert untracked(mono) == []


def test_consolidation_stops_at_nested_clone(tmp_path: Path):
    """Consolidation must not absorb entries from a nested independent repo.

    A separate clone or worktree checked out inside the monorepo tree has a
    .ewasd_gitignore whose paths are relative to *its* root, so importing them
    into the parent produces wrong paths and cross-repo noise.
    """
    mono = init_repo(tmp_path / "mono")
    subdir = mono / "projects" / "sub"
    subdir.mkdir(parents=True)

    # An unrelated repo that happens to live inside the monorepo tree.
    nested = init_repo(mono / "nested-checkout")
    (nested / GITIGNORE_FILENAME).write_text(
        "# Auto-generated by ewasd\nFOREIGN_ENTRY.md\nprojects/other/FOREIGN_NESTED.md\n"
    )

    sub_repo = Repo("sub", "url", make_link_dir(tmp_path / "ws" / "sub", "SUB.md"))
    sub_repo.link_all(subdir)

    consolidated = (mono / GITIGNORE_FILENAME).read_text()
    assert "projects/sub/SUB.md" in consolidated
    assert "FOREIGN_ENTRY.md" not in consolidated, (
        "consolidation crossed into a nested git repository"
    )
    assert "FOREIGN_NESTED.md" not in consolidated


def test_consolidation_stops_at_submodule_boundary(tmp_path: Path):
    """Submodules and linked worktrees mark their root with a .git *file*."""
    mono = init_repo(tmp_path / "mono")
    subdir = mono / "projects" / "sub"
    subdir.mkdir(parents=True)

    # Submodules/worktrees use a `.git` file containing a gitdir: pointer.
    submodule = mono / "vendor" / "libthing"
    submodule.mkdir(parents=True)
    (submodule / ".git").write_text("gitdir: ../../.git/modules/libthing\n")
    (submodule / GITIGNORE_FILENAME).write_text("# Auto-generated by ewasd\nSUBMODULE_ENTRY.md\n")

    sub_repo = Repo("sub", "url", make_link_dir(tmp_path / "ws" / "sub", "SUB.md"))
    sub_repo.link_all(subdir)

    consolidated = (mono / GITIGNORE_FILENAME).read_text()
    assert "projects/sub/SUB.md" in consolidated
    assert "SUBMODULE_ENTRY.md" not in consolidated, "consolidation descended into a submodule"


def test_worktree_does_not_clobber_main_excludes(tmp_path: Path):
    """Running ewasd in a linked worktree must not repoint the main checkout.

    Worktrees share .git/config, so a plain `git config core.excludesFile`
    from a worktree overwrites the main checkout's setting for every worktree.
    Removing that worktree then breaks excludes everywhere.
    """
    main = init_repo(tmp_path / "main")
    wt = tmp_path / "wt"
    git(main, "worktree", "add", "-q", str(wt), "-b", "feature")

    main_repo = Repo("main", "url", make_link_dir(tmp_path / "ws" / "main", "MAIN.md"))
    wt_repo = Repo("wt", "url", make_link_dir(tmp_path / "ws" / "wt", "WT.md"))

    main_repo.link_all(main)
    main_excludes_before = excludes_file(main)
    assert main_excludes_before == expected_excludes(main)

    # Now operate inside the linked worktree.
    wt_repo.link_all(wt)

    assert excludes_file(main) == main_excludes_before, (
        "worktree run repointed the main checkout's core.excludesFile"
    )
    assert excludes_file(wt) == expected_excludes(wt)

    # Both checkouts must actually be clean.
    assert untracked(main) == []
    assert untracked(wt) == []


def test_worktree_excludes_survive_worktree_removal(tmp_path: Path):
    """Deleting a worktree must leave the main checkout's excludes intact."""
    main = init_repo(tmp_path / "main")
    wt = tmp_path / "wt"
    git(main, "worktree", "add", "-q", str(wt), "-b", "feature")

    Repo("main", "url", make_link_dir(tmp_path / "ws" / "main", "MAIN.md")).link_all(main)
    Repo("wt", "url", make_link_dir(tmp_path / "ws" / "wt", "WT.md")).link_all(wt)

    git(main, "worktree", "remove", "--force", str(wt))

    assert excludes_file(main) == expected_excludes(main)
    assert untracked(main) == []
