#!/usr/bin/env bash
set -euo pipefail

ROOT=$(unset CDPATH; cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)
mkdir -p "$ROOT/test-results"
FIXTURE=$(mktemp -d "$ROOT/test-results/ewasd-replacement-fixture.XXXXXX")
trap 'rm -rf -- "$FIXTURE"' EXIT INT TERM

LEGACY="$FIXTURE/legacy"
SOURCE="$LEGACY/repos/demo"
REPOSITORY="$FIXTURE/repository"
STATE="$FIXTURE/state"
INSTALL_BIN="$FIXTURE/bin/ewasd"
mkdir -p "$SOURCE" "$REPOSITORY" "$FIXTURE/bin"
git -C "$REPOSITORY" init -q
git -C "$REPOSITORY" remote add origin git@github.com:example/demo.git

cat > "$LEGACY/editors.toml" <<'EOF'
[repos.demo]
repo = "git@github.com:example/demo.git"
link_dir = "repos/demo"
EOF
printf 'legacy fixture\n' > "$SOURCE/AGENT.md"
ln -s "$SOURCE/AGENT.md" "$REPOSITORY/AGENT.md"
cat > "$REPOSITORY/.ewasd_gitignore" <<'EOF'
# Auto-generated by ewasd
# Editor configuration files
.ewasd_gitignore
AGENT.md
EOF
git -C "$REPOSITORY" config core.excludesFile "$REPOSITORY/.ewasd_gitignore"

EWASD_LEGACY_WORKSPACE="$LEGACY" \
EWASD_SCAN_ROOTS="$FIXTURE" \
EWASD_HOME="$STATE" \
EWASD_BUILD_MODE=go \
EWASD_INSTALL_MODE=copy \
EWASD_INSTALL_BIN="$INSTALL_BIN" \
  bash "$ROOT/scripts/replace-python-with-go.sh"

test "$($INSTALL_BIN --version)" = "ewasd 1.1.0"
test ! -e "$REPOSITORY/.ewasd_gitignore"
test -f "$LEGACY/editors.toml"
test "$(cat "$SOURCE/AGENT.md")" = "legacy fixture"
test "$(cat "$REPOSITORY/AGENT.md")" = "legacy fixture"
case "$(readlink -f "$REPOSITORY/AGENT.md")" in
  "$STATE"/profiles/*/files/AGENT.md) ;;
  *) echo "migrated link does not point into Go state" >&2; exit 1 ;;
esac
test -f "$STATE/legacy/migration-receipt.json"
test -f "$STATE/legacy/replacement-receipt.txt"
test -z "$(find "$STATE/transactions" -mindepth 1 -maxdepth 1 -print -quit)"

STATE_HASH=$(sha256sum "$STATE/state.json" | cut -d' ' -f1)
EWASD_LEGACY_WORKSPACE="$LEGACY" \
EWASD_SCAN_ROOTS="$FIXTURE" \
EWASD_HOME="$STATE" \
EWASD_BUILD_MODE=go \
EWASD_INSTALL_MODE=copy \
EWASD_INSTALL_BIN="$INSTALL_BIN" \
  bash "$ROOT/scripts/replace-python-with-go.sh"
test "$(sha256sum "$STATE/state.json" | cut -d' ' -f1)" = "$STATE_HASH"

find_nix() {
  if command -v nix >/dev/null 2>&1; then command -v nix; return; fi
  local candidate
  for candidate in /nix/var/nix/profiles/default/bin/nix /nix/store/*-nix-*/bin/nix; do
    if [ -x "$candidate" ]; then printf '%s\n' "$candidate"; return; fi
  done
  return 1
}

if NIX=$(find_nix); then
  NIX_FIXTURE="$FIXTURE/nix"
  OLD_PACKAGE="$FIXTURE/ewasd"
  PROFILE="$NIX_FIXTURE/profile"
  mkdir -p "$OLD_PACKAGE/bin" "$NIX_FIXTURE"
  cat > "$OLD_PACKAGE/bin/ewasd" <<'EOF'
#!/usr/bin/env bash
printf 'ewasd 0.9.0\n'
EOF
  chmod 0755 "$OLD_PACKAGE/bin/ewasd"
  OLD_STORE=$($NIX store add-path "$OLD_PACKAGE")
  $NIX profile add --profile "$PROFILE" "$OLD_STORE"
  test "$("$PROFILE/bin/ewasd" --version)" = "ewasd 0.9.0"

  EWASD_LEGACY_WORKSPACE="$FIXTURE/no-legacy" \
  EWASD_SCAN_ROOTS="$FIXTURE" \
  EWASD_HOME="$NIX_FIXTURE/state" \
  EWASD_BUILD_MODE=nix \
  EWASD_INSTALL_MODE=nix \
  EWASD_NIX_PROFILE="$PROFILE" \
    bash "$ROOT/scripts/replace-python-with-go.sh"
  test "$("$PROFILE/bin/ewasd" --version)" = "ewasd 1.1.0"
  find "$NIX_FIXTURE/state/legacy" -maxdepth 1 -type d -name 'installer-source-*' | grep -q .

  # A second Nix-mode run must leave the active command intact and v1.
  EWASD_LEGACY_WORKSPACE="$FIXTURE/no-legacy" \
  EWASD_SCAN_ROOTS="$FIXTURE" \
  EWASD_HOME="$NIX_FIXTURE/state" \
  EWASD_BUILD_MODE=nix \
  EWASD_INSTALL_MODE=nix \
  EWASD_NIX_PROFILE="$PROFILE" \
    bash "$ROOT/scripts/replace-python-with-go.sh"
  test "$("$PROFILE/bin/ewasd" --version)" = "ewasd 1.1.0"
  test "$($NIX profile list --profile "$PROFILE" --json | grep -oE '/nix/store/[a-z0-9]+-ewasd-[^" ]+' | sort -u | wc -l)" -eq 1
fi

printf 'replacement fixture passed\n'
