package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"testing"

	"github.com/dmitrii-galantsev/ewasd/internal/engine"
	"github.com/dmitrii-galantsev/ewasd/internal/store"
)

func TestLoadConsoleTokenPersistsSecureRandomToken(t *testing.T) {
	t.Setenv("EWASD_TOKEN", "")
	root := t.TempDir()
	first, err := loadConsoleToken(root, "")
	if err != nil || len(first) != 64 {
		t.Fatalf("generate token: len=%d err=%v", len(first), err)
	}
	second, err := loadConsoleToken(root, "")
	if err != nil || second != first {
		t.Fatalf("token was not stable: %q %v", second, err)
	}
	info, err := os.Stat(filepath.Join(root, "console.token"))
	if err != nil || info.Mode().Perm() != 0o600 {
		t.Fatalf("token permissions = %v, %v", info.Mode().Perm(), err)
	}
}

func TestLoadConsoleTokenRejectsWeakOverride(t *testing.T) {
	t.Parallel()
	if _, err := loadConsoleToken(t.TempDir(), "short"); err == nil {
		t.Fatal("weak token override was accepted")
	}
}

func TestMigrateLegacyCommandImportsAndRetiresPythonMarker(t *testing.T) {
	root := t.TempDir()
	legacy := filepath.Join(root, "legacy")
	legacySource := filepath.Join(legacy, "repos", "demo")
	repository := filepath.Join(root, "repository")
	dataRoot := filepath.Join(root, "go-state")
	if err := os.MkdirAll(legacySource, 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.Mkdir(repository, 0o755); err != nil {
		t.Fatal(err)
	}
	runGit(t, repository, "init", "-q")
	runGit(t, repository, "remote", "add", "origin", "git@github.com:example/demo.git")
	if err := os.WriteFile(filepath.Join(legacy, "editors.toml"), []byte("[repos.demo]\nrepo = \"git@github.com:example/demo.git\"\nlink_dir = \"repos/demo\"\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	legacyFile := filepath.Join(legacySource, "AGENT.md")
	if err := os.WriteFile(legacyFile, []byte("legacy content\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	target := filepath.Join(repository, "AGENT.md")
	if err := os.Symlink(legacyFile, target); err != nil {
		t.Fatal(err)
	}
	marker := filepath.Join(repository, ".ewasd_gitignore")
	if err := os.WriteFile(marker, []byte("# Auto-generated by ewasd\n# Editor configuration files\n.ewasd_gitignore\nAGENT.md\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	runGit(t, repository, "config", "core.excludesFile", marker)
	t.Setenv("EWASD_HOME", dataRoot)
	if err := run([]string{"migrate-legacy", "--workspace", legacy, "--scan-root", root, "--apply", "--json"}); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(marker); !os.IsNotExist(err) {
		t.Fatalf("legacy marker remains: %v", err)
	}
	resolved, err := filepath.EvalSymlinks(target)
	if err != nil {
		t.Fatal(err)
	}
	if relative, err := filepath.Rel(dataRoot, resolved); err != nil || relative == ".." || len(relative) < len("profiles") || relative[:len("profiles")] != "profiles" {
		t.Fatalf("target does not point into Go state: %s, %v", resolved, err)
	}
	if data, _ := os.ReadFile(target); string(data) != "legacy content\n" {
		t.Fatalf("migrated bytes changed: %q", data)
	}
	if data, _ := os.ReadFile(legacyFile); string(data) != "legacy content\n" {
		t.Fatalf("legacy backup changed: %q", data)
	}
	if _, err := os.Stat(filepath.Join(dataRoot, "legacy", "migration-receipt.json")); err != nil {
		t.Fatalf("migration receipt missing: %v", err)
	}
}

func TestCLIInfersLinkAndCleanAppliesByDefault(t *testing.T) {
	root := t.TempDir()
	stateRoot := filepath.Join(root, "state")
	template := filepath.Join(root, "template")
	clone := filepath.Join(root, "clone")
	for _, repository := range []string{template, clone} {
		if err := os.Mkdir(repository, 0o755); err != nil {
			t.Fatal(err)
		}
		runGit(t, repository, "init", "-q")
		runGit(t, repository, "remote", "add", "origin", "git@github.com:example/inferred.git")
	}
	t.Setenv("EWASD_HOME", stateRoot)
	stateStore, err := store.New(stateRoot)
	if err != nil {
		t.Fatal(err)
	}
	domainEngine := engine.New(stateStore)
	project, _, err := domainEngine.Register(template, "inferred")
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(template, "AGENT.md"), []byte("shared"), 0o600); err != nil {
		t.Fatal(err)
	}
	plan, _ := domainEngine.PlanAdopt(project.ID, "AGENT.md")
	if _, err := domainEngine.Adopt(project.ID, "AGENT.md", plan.ExpectedRevision, plan.Fingerprint); err != nil {
		t.Fatal(err)
	}
	if err := run([]string{"link", "--root", clone}); err != nil {
		t.Fatal(err)
	}
	if info, err := os.Lstat(filepath.Join(clone, "AGENT.md")); err != nil || info.Mode()&os.ModeSymlink == 0 {
		t.Fatalf("CLI link did not create symlink: %v, %v", info, err)
	}
	if err := os.WriteFile(filepath.Join(clone, "junk.tmp"), []byte("junk"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := run([]string{"clean", "--root", clone}); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(clone, "junk.tmp")); err != nil {
		t.Fatalf("clean dry-run changed junk: %v", err)
	}
	cleanPlan, err := domainEngine.PlanClean(clone, "", engine.CleanOptions{Mode: "untracked"})
	if err != nil {
		t.Fatal(err)
	}
	if err := run([]string{"clean", "--root", clone, "--apply", "--revision", fmt.Sprint(cleanPlan.ExpectedRevision), "--fingerprint", cleanPlan.Fingerprint}); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(clone, "junk.tmp")); !os.IsNotExist(err) {
		t.Fatalf("CLI clean did not remove junk: %v", err)
	}
	if _, err := os.Stat(filepath.Join(clone, "AGENT.md")); err != nil {
		t.Fatalf("CLI clean removed managed link: %v", err)
	}
}

func runGit(t *testing.T, cwd string, args ...string) {
	t.Helper()
	command := exec.Command("git", args...)
	command.Dir = cwd
	if output, err := command.CombinedOutput(); err != nil {
		t.Fatalf("git %v: %v: %s", args, err, output)
	}
}
