"""Core domain objects and helpers for ewasd.

Separable from CLI so it can be imported and unit tested.
"""

import os
import re
import shutil
import subprocess
import sys
from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from pathlib import Path

try:  # Optional color support
    from termcolor import colored  # type: ignore
except Exception:  # pragma: no cover - optional dependency

    def colored(text: str, _color: str) -> str:  # type: ignore
        return text


import tomllib  # Python 3.11+ built-in for reading TOML

import tomlkit  # For TOML writing that preserves formatting

# Module-level constants
GITIGNORE_FILENAME = ".ewasd_gitignore"
IGNORED_VCS_DIRS = frozenset({".git", ".svn"})


def get_config_dir() -> Path:
    """Return XDG_CONFIG_HOME/ewasd, creating nothing."""
    base = Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config"))
    return base / "ewasd"


def _read_tool_config() -> dict:  # type: ignore[type-arg]
    """Load ~/.config/ewasd/config.toml if it exists."""
    config_file = get_config_dir() / "config.toml"
    if config_file.exists():
        with config_file.open("rb") as f:
            return tomllib.load(f)
    return {}


def get_workspace_dir(cli_override: str | None = None) -> Path:
    """Resolve workspace directory in priority order.

    1. CLI flag (--workspace)
    2. EWASD_WORKSPACE env var
    3. workspace key in ~/.config/ewasd/config.toml
    4. $XDG_DATA_HOME/ewasd/ (if it exists)
    5. Legacy fallback (backwards compat during transition)
    6. Default to XDG data home even if it doesn't exist yet
    """
    # 1. CLI flag
    if cli_override:
        return Path(cli_override).expanduser().resolve()
    # 2. Env var
    env = os.environ.get("EWASD_WORKSPACE")
    if env:
        return Path(env).expanduser().resolve()
    # 3. config.toml
    tool_cfg = _read_tool_config()
    if "workspace" in tool_cfg:
        return Path(tool_cfg["workspace"]).expanduser().resolve()
    # 4. XDG data home
    data_home = Path(os.environ.get("XDG_DATA_HOME", Path.home() / ".local" / "share"))
    xdg_path = data_home / "ewasd"
    if xdg_path.exists():
        return xdg_path
    # 5. Legacy fallback (backwards compat during transition)
    legacy = Path(__file__).resolve().parent.parent
    if (legacy / "editors.toml").exists():
        return legacy
    legacy2 = Path.home() / "git" / "editor_workspaces"
    if (legacy2 / "editors.toml").exists():
        return legacy2
    # 6. Default to XDG even if it doesn't exist yet
    return xdg_path


def get_remote_keys() -> list[str]:
    """Load remote keys from config, default to just origin."""
    cfg = _read_tool_config()
    return cfg.get("remote_keys", ["remote.origin.url"])


def warn(msg: str) -> None:
    print(colored(f"WARN: {msg}", "yellow"), file=sys.stderr)


def success(msg: str) -> None:
    print(colored(msg, "green"))


def _detect_git_root(cwd: Path, resolved_cwd: Path) -> tuple[Path | None, str]:
    """Detect git root and compute path prefix for monorepo support.

    Returns (git_root, path_prefix) where path_prefix is "" for non-monorepo.
    """
    git_root: Path | None = None
    path_prefix = ""
    try:
        out = subprocess.check_output(
            ["git", "rev-parse", "--show-toplevel"], cwd=str(cwd), text=True
        ).strip()
        if out:
            git_root = Path(out).resolve()
            if resolved_cwd != git_root:
                rel = resolved_cwd.relative_to(git_root)
                path_prefix = str(rel) + "/"
    except (OSError, subprocess.CalledProcessError):
        pass
    return git_root, path_prefix


def _write_local_gitignore(cwd: Path, linked_items: list[str], path_prefix: str) -> Path:
    """Write a local .ewasd_gitignore file with this project's entries. Returns the path."""
    local_gitignore = cwd / GITIGNORE_FILENAME
    lines = ["# Auto-generated by ewasd", "# Editor configuration files"]
    lines.append(f"{path_prefix}{GITIGNORE_FILENAME}")
    for item in linked_items:
        lines.append(f"{path_prefix}{item}")
    local_gitignore.write_text("\n".join(lines) + "\n")
    return local_gitignore


def _consolidate_monorepo_gitignores(git_root: Path) -> Path:
    """Collect all .ewasd_gitignore files under git_root into one consolidated file."""
    consolidated_file = git_root / GITIGNORE_FILENAME
    all_entries: set[str] = set()

    try:
        for gitignore_path in git_root.rglob(GITIGNORE_FILENAME):
            try:
                content = gitignore_path.read_text()
                for line in content.splitlines():
                    line = line.strip()
                    if line and not line.startswith("#"):
                        all_entries.add(line)
            except OSError:
                pass
    except OSError:
        pass

    all_entries.add(GITIGNORE_FILENAME)

    lines = [
        "# Auto-generated by ewasd",
        "# Consolidated editor configuration files from all projects",
    ]
    for entry in sorted(all_entries):
        lines.append(entry)
    consolidated_file.write_text("\n".join(lines) + "\n")
    return consolidated_file


def _set_git_excludes(gitignore_path: Path, cwd: Path) -> None:
    """Configure git to use the given file as core.excludesFile."""
    try:
        subprocess.run(
            ["git", "config", "core.excludesFile", str(gitignore_path.resolve())],
            cwd=str(cwd),
            check=True,
            capture_output=True,
        )
    except (OSError, subprocess.CalledProcessError) as e:
        warn(f"Failed to configure git excludes file: {e}")


@dataclass
class Repo:
    """A configured repository entry from editors.toml."""

    name: str
    git_url: str
    link_dir: Path

    def get_configs(self) -> list[str]:
        """Return candidate config entries (files or directories) at top level.

        Currently returns everything in link_dir (non-recursive). A future enhancement
        might allow filtering (e.g., only dotfiles) via a predicate parameter.
        """
        if not self.link_dir.exists():
            warn(f"Directory {self.link_dir} does not exist")
            return []
        entries: list[str] = []
        for child in sorted(self.link_dir.iterdir()):
            # Skip version control internals just in case
            if child.name in IGNORED_VCS_DIRS:
                continue
            entries.append(child.name)
        return entries

    def link_directory(
        self, src_dir: Path, dst_dir: Path, rel_prefix: str = "", *, dry_run: bool = False
    ) -> list[str]:
        """Recursively link files from src_dir into dst_dir.

        Returns list of relative paths that were (or would be) symlinked.
        """
        linked_paths: list[str] = []

        if not src_dir.exists() or not src_dir.is_dir():
            return linked_paths

        for child in sorted(src_dir.iterdir()):
            if child.name in IGNORED_VCS_DIRS:
                continue

            src_item = src_dir / child.name
            dst_item = dst_dir / child.name
            rel_path = f"{rel_prefix}{child.name}"

            if src_item.is_dir():
                if dst_item.exists() and dst_item.is_dir():
                    # Both are directories, recurse
                    nested_paths = self.link_directory(
                        src_item, dst_item, f"{rel_path}/", dry_run=dry_run
                    )
                    linked_paths.extend(nested_paths)
                elif not dst_item.exists():
                    # Target dir doesn't exist, symlink the whole directory
                    if dry_run:
                        print(f"  Would link {src_item} -> {dst_item}")
                    else:
                        success(f"Linked {src_item} to {dst_item}")
                        dst_item.symlink_to(src_item)
                    linked_paths.append(rel_path)
                # If dst_item exists but is a file, skip with warning
                elif dst_item.is_file():
                    warn(f"File exists where directory expected! Skipping {rel_path}")
            # It's a file
            elif dst_item.is_symlink():
                # Already a symlink, track it
                linked_paths.append(rel_path)
            elif dst_item.exists():
                # Real file exists, skip
                warn(f"File exists! Skipping {rel_path}")
            else:
                # Link the file
                if dry_run:
                    print(f"  Would link {src_item} -> {dst_item}")
                else:
                    success(f"Linked {src_item} to {dst_item}")
                    dst_item.symlink_to(src_item)
                linked_paths.append(rel_path)

        return linked_paths

    def link_any(self, target_name: str, cwd: Path, *, dry_run: bool = False) -> list[str]:
        """Link a single config entry (file or directory).

        Returns list of relative paths that were (or would be) symlinked.
        """
        src = self.link_dir / target_name
        dst = cwd / target_name

        if not src.exists():
            warn(f"No file found at {src}")
            return []

        # Handle directories
        if src.is_dir():
            if dst.is_symlink():
                warn(f"Symbolic link exists! Skipping {target_name}")
                return [target_name]
            elif dst.exists() and dst.is_dir():
                # Both are directories - recurse into it
                return self.link_directory(src, dst, f"{target_name}/", dry_run=dry_run)
            elif dst.exists():
                warn(f"File exists where directory expected! Skipping {target_name}")
                return []
            else:
                # Target dir doesn't exist, symlink whole directory
                if dry_run:
                    print(f"  Would link {src} -> {dst}")
                else:
                    success(f"Linked {src} to {dst}")
                    dst.symlink_to(src)
                return [target_name]

        # Handle files
        if dst.is_symlink():
            warn(f"Symbolic link exists! Skipping {target_name}")
            return [target_name]
        if dst.exists():
            warn(f"File exists! Skipping {target_name}")
            return []
        if dry_run:
            print(f"  Would link {src} -> {dst}")
        else:
            success(f"Linked {src} to {dst}")
            dst.symlink_to(src)
        return [target_name]

    def update_gitignore(self, cwd: Path, linked_items: list[str]) -> None:
        """Create/update .ewasd_gitignore with only actually symlinked items.

        For monorepos: consolidates all .ewasd_gitignore files into a single
        file at the git root so that all projects' symlinks are properly ignored.
        """
        if not linked_items:
            return

        resolved_cwd = cwd.resolve()
        git_root, path_prefix = _detect_git_root(cwd, resolved_cwd)

        local_gitignore = _write_local_gitignore(cwd, linked_items, path_prefix)

        if git_root and git_root != resolved_cwd:
            target_gitignore = _consolidate_monorepo_gitignores(git_root)
        else:
            target_gitignore = local_gitignore

        _set_git_excludes(target_gitignore, cwd)

    def link_all(self, cwd: Path, *, dry_run: bool = False) -> None:
        linked_items = []
        for cfg in self.get_configs():
            paths = self.link_any(cfg, cwd, dry_run=dry_run)
            linked_items.extend(paths)
        # Auto-update gitignore with only successfully linked items
        if not dry_run:
            self.update_gitignore(cwd, linked_items)

    def iter_git_clean_args(self) -> Iterable[str]:
        # Produces tokens suitable for: git clean -fdx $(ewasd git-clean-args)
        # Exclude the gitignore file itself
        yield "-e"
        yield GITIGNORE_FILENAME
        # Exclude all config files
        for cfg in self.get_configs():
            yield "-e"
            yield cfg


@dataclass
class SymlinkStatus:
    """Result of checking a single symlink."""

    path: Path
    target: Path
    ok: bool
    reason: str  # "ok", "broken", "wrong_target"


def check_symlink_health(cwd: Path, repo: "Repo") -> list[SymlinkStatus]:
    """Check all expected symlinks for a repo in cwd. Returns list of statuses."""
    results: list[SymlinkStatus] = []
    for cfg_name in repo.get_configs():
        _check_entry(cwd, repo.link_dir, cfg_name, results)
    # Also check the gitignore file
    gi = cwd / GITIGNORE_FILENAME
    if gi.is_symlink():
        results.append(SymlinkStatus(
            path=gi, target=Path(os.readlink(gi)),
            ok=gi.exists(), reason="ok" if gi.exists() else "broken",
        ))
    elif gi.exists():
        results.append(SymlinkStatus(path=gi, target=gi, ok=True, reason="ok"))
    return results


def _check_entry(
    cwd: Path, link_dir: Path, name: str, results: list[SymlinkStatus]
) -> None:
    """Recursively check a config entry (file or directory) for symlink health."""
    dst = cwd / name
    src = link_dir / name
    if dst.is_symlink():
        target = Path(os.readlink(dst))
        if not dst.exists():
            results.append(SymlinkStatus(path=dst, target=target, ok=False, reason="broken"))
        elif dst.resolve() != src.resolve():
            results.append(SymlinkStatus(
                path=dst, target=target, ok=False, reason="wrong_target"
            ))
        else:
            results.append(SymlinkStatus(path=dst, target=target, ok=True, reason="ok"))
    elif dst.is_dir() and src.is_dir():
        # Recurse into matching directories
        for child in sorted(src.iterdir()):
            if child.name in IGNORED_VCS_DIRS:
                continue
            _check_entry(dst, src, child.name, results)


class ConfigParser:
    """Load and provide access to editors.toml configuration."""

    def __init__(self, workspace_dir: Path | None = None, toml_path: Path | None = None):
        if toml_path:
            self.toml_path = toml_path
            self.workspace_dir = toml_path.parent
        else:
            self.workspace_dir = workspace_dir or get_workspace_dir()
            self.toml_path = self.workspace_dir / "editors.toml"
        with self.toml_path.open("rb") as f:
            self.parsed = tomllib.load(f)
        if "repos" not in self.parsed:
            raise ValueError("Invalid editors.toml: missing [repos] table")
        # Validate each repo entry has required fields
        for name, entry in self.parsed["repos"].items():
            if not isinstance(entry, dict):
                raise ValueError(f"Invalid editors.toml: [repos.{name}] must be a table")
            missing = [f for f in ("repo", "link_dir") if f not in entry]
            if missing:
                raise ValueError(
                    f"Invalid editors.toml: [repos.{name}] missing required field(s): "
                    + ", ".join(missing)
                )

    def repo_names(self) -> Sequence[str]:
        return list(self.parsed["repos"].keys())

    def get_repo(self, name: str) -> Repo:
        data = self.parsed["repos"].get(name)
        if not data:
            raise KeyError(f"Repo [{name}] not found in editors.toml")
        git_url = data.get("repo")
        link_dir_raw = data.get("link_dir")
        if not git_url or not link_dir_raw:
            raise ValueError(f"Repo [{name}] missing required fields")
        link_dir = self.workspace_dir / link_dir_raw
        return Repo(name=name, git_url=git_url, link_dir=link_dir)

    def create_repo_entry(self, name: str, cwd: Path) -> Repo | None:
        """Auto-create a new repo entry by inferring from current context."""
        # Try to get git remote for URL
        try:
            remotes = collect_remotes()
            git_url = remotes[0] if remotes else f"https://example.com/{name}.git"
        except (OSError, subprocess.CalledProcessError):  # pragma: no cover
            git_url = f"https://example.com/{name}.git"

        # Determine link_dir based on existing patterns or default
        # Look for existing patterns to infer vendor/category
        existing_entries = list(self.parsed["repos"].values())
        link_dir_raw = f"repos/{name}"  # default

        if existing_entries:
            # Try to infer pattern from similar entries
            for entry in existing_entries:
                existing_link = entry.get("link_dir", "")
                if "/" in existing_link:
                    parts = existing_link.split("/")
                    if len(parts) >= 2:
                        # Use same vendor/category structure
                        vendor_path = "/".join(parts[:-1])
                        link_dir_raw = f"{vendor_path}/{name}"
                        break

        # Write new entry using tomlkit to preserve formatting and handle escaping
        try:
            toml_content = self.toml_path.read_text()
            doc = tomlkit.parse(toml_content)

            new_table = tomlkit.table()
            new_table.add("repo", git_url)
            new_table.add("link_dir", link_dir_raw)
            doc["repos"].add(name, new_table)  # type: ignore[union-attr]

            self.toml_path.write_text(tomlkit.dumps(doc))

            # Reload parsed data
            with self.toml_path.open("rb") as f:
                self.parsed = tomllib.load(f)

            link_dir = self.workspace_dir / link_dir_raw
            return Repo(name=name, git_url=git_url, link_dir=link_dir)

        except (OSError, tomlkit.exceptions.TOMLKitError) as e:  # pragma: no cover
            warn(f"Failed to write to {self.toml_path}: {e}")
            return None


def collect_remotes() -> list[str]:
    out: list[str] = []
    for key in get_remote_keys():
        try:
            result = subprocess.run(
                ["git", "config", "--get", key], capture_output=True, text=True, check=False
            )
            url = result.stdout.strip()
            if url:
                out.append(url)
        except OSError:
            pass
    return out


RE_REPO_NAME = re.compile(r".*/([^/]+?)(?:\.git|/?|)$")


def find_repo_name(remotes: Sequence[str]) -> str | None:
    for url in remotes:
        m = RE_REPO_NAME.match(url)
        if m:
            return m.group(1)
    return None


def build_git_clean_tokens(repo: Repo) -> list[str]:
    return list(repo.iter_git_clean_args())


def find_repo_name_in_path(
    cwd: Path, known_repo_names: Sequence[str], git_root: Path | None = None
) -> str | None:
    """Attempt to detect a repo name by examining path components.

    This enables monorepo support: if the git remote refers to a monorepo (e.g. 'rocm-systems')
    but you're working inside a subdirectory whose leaf component matches a configured repo
    (e.g. 'projects/rdc'), we use that leaf.
    Preference: choose the *deepest* path component that matches a known repo for specificity.
    """
    # Establish search path relative to git root if provided, else full path.
    parts = list(cwd.parts)
    if git_root and cwd.is_relative_to(git_root):
        rel = cwd.relative_to(git_root)
        parts = [p for p in rel.parts]
    matches = [p for p in parts if p in known_repo_names]
    if matches:
        return matches[-1]
    return None


def detect_repo_name(
    *,
    project_override: str | None,
    remotes: Sequence[str],
    cwd: Path,
    known_repo_names: Sequence[str],
    trace: list[str] | None = None,
) -> str | None:
    """Unified repo name detection with override, path-first for monorepo, then remote fallback.

    If *trace* is provided, strategy results are appended for diagnostics.
    """
    if project_override:
        if project_override in known_repo_names:
            return project_override
        if trace is not None:
            trace.append(
                f"--project '{project_override}' not found in known repos: "
                + ", ".join(known_repo_names) if known_repo_names else "(none configured)"
            )
        return None

    # Path-based detection first (monorepo subdir case)
    git_root: Path | None = None
    try:
        out = subprocess.check_output(
            ["git", "rev-parse", "--show-toplevel"], cwd=str(cwd), text=True
        ).strip()
        if out:
            git_root = Path(out)
    except (OSError, subprocess.CalledProcessError):  # pragma: no cover - non-critical
        if trace is not None:
            trace.append("git root detection failed (not a git repo?)")
    path_match = find_repo_name_in_path(cwd, known_repo_names, git_root)
    if path_match:
        return path_match
    if trace is not None:
        trace.append(f"path-based detection: no path component matches known repos (cwd={cwd})")

    # Remote fallback
    remote_match = find_repo_name(remotes)
    if remote_match and remote_match in known_repo_names:
        return remote_match
    if trace is not None:
        if not remotes:
            trace.append("remote detection: no git remotes found")
        elif remote_match:
            trace.append(
                f"remote detection: extracted '{remote_match}' from remotes but it's "
                f"not in known repos: {', '.join(known_repo_names)}"
            )
        else:
            trace.append(f"remote detection: could not extract repo name from {remotes}")
    return None


STARTER_TOML = """\
# ewasd workspace configuration
# Add repos here. Each entry maps a git repo to a directory of config files.
#
# [repos.my-project]
#     repo = "https://github.com/user/my-project.git"
#     link_dir = "repos/my-project"
[repos]
"""


def find_legacy_workspace() -> Path | None:
    """Check common legacy locations for an existing workspace."""
    import __main__  # noqa: PLC0415

    candidates = [
        Path(__main__.__file__).resolve().parent if hasattr(__main__, "__file__") else None,
        Path(__file__).resolve().parent.parent,
        Path.home() / "git" / "editor_workspaces",
        Path.home() / "git" / "ewasd",
    ]
    for candidate in candidates:
        if candidate and (candidate / "editors.toml").exists():
            return candidate
    return None


def init_workspace(ws: Path, from_git: str | None) -> int:
    """Initialize a new ewasd workspace. Returns exit code."""
    if from_git:
        subprocess.run(["git", "clone", from_git, str(ws)], check=True)
        return 0

    legacy = find_legacy_workspace()
    if legacy and legacy.resolve() != ws.resolve() and not (ws / "editors.toml").exists():
        print(f"Found existing workspace at {legacy}")
        print(f"Copying to {ws} ...")
        ws.mkdir(parents=True, exist_ok=True)
        shutil.copy2(legacy / "editors.toml", ws / "editors.toml")
        legacy_repos = legacy / "repos"
        if legacy_repos.is_dir():
            dest_repos = ws / "repos"
            if dest_repos.exists():
                shutil.rmtree(dest_repos)
            shutil.copytree(legacy_repos, dest_repos, symlinks=True)
        success(f"Migrated workspace from {legacy} to {ws}")
        print("Run 'ewasd migrate --old-workspace " + str(legacy) + "' to fix existing symlinks.")
        return 0

    ws.mkdir(parents=True, exist_ok=True)
    (ws / "repos").mkdir(exist_ok=True)
    toml = ws / "editors.toml"
    if not toml.exists():
        toml.write_text(STARTER_TOML)
    success(f"Initialized workspace at {ws}")
    return 0


def migrate_symlinks(
    ws: Path, old_ws: Path, target_dir: Path, dry_run: bool
) -> tuple[int, int]:
    """Fix broken symlinks by repointing from old workspace to new workspace.

    Returns (fixed_count, broken_count).
    """
    old_ws_str = str(old_ws)
    new_ws_str = str(ws)
    fixed = 0
    broken = 0

    for item in target_dir.rglob("*"):
        if not item.is_symlink():
            continue
        try:
            link_target = os.readlink(item)
        except OSError:
            continue
        if old_ws_str not in link_target:
            continue
        new_target = link_target.replace(old_ws_str, new_ws_str, 1)
        if Path(new_target).exists():
            if dry_run:
                print(f"  Would fix: {item} -> {new_target}")
            else:
                item.unlink()
                item.symlink_to(new_target)
                success(f"  Fixed: {item} -> {new_target}")
            fixed += 1
        else:
            warn(f"  Cannot fix: {item} -> {link_target} (new target {new_target} not found)")
            broken += 1

    return fixed, broken


def add_file_to_repo(
    filenames: list[str],
    cwd: Path,
    cfg: "ConfigParser",
    project_override: str | None,
) -> int:
    """Move file(s) to central repo and create symlink back. Returns exit code."""
    # Validate all files exist first
    missing_files = [f for f in filenames if not (cwd / f).exists()]
    if missing_files:
        for filename in missing_files:
            warn(f"File {filename} does not exist in current directory")
        return 1

    # Determine repo name
    if project_override:
        repo_name = project_override
    else:
        repo_name = detect_repo_name(
            project_override=None,
            remotes=collect_remotes(),
            cwd=cwd,
            known_repo_names=cfg.repo_names(),
        )
        if not repo_name:
            remotes = collect_remotes()
            if remotes:
                repo_name = find_repo_name(remotes)
            if not repo_name:
                path_parts = [p for p in cwd.parts if p and p != "/"]
                if path_parts:
                    repo_name = path_parts[-1]

    if not repo_name:
        warn("Unable to determine repository name for --add-file operation")
        warn("Please use --project <name> to specify explicitly")
        return 1

    # Ensure project exists in config
    try:
        repo = cfg.get_repo(repo_name)
    except KeyError:
        print(f"Project '{repo_name}' not found in config. Creating...")
        repo = cfg.create_repo_entry(repo_name, cwd)
        if not repo:
            warn(f"Failed to create project entry for '{repo_name}'")
            return 1
        success(f"Created project entry: {repo_name} -> {repo.link_dir}")
    except ValueError as exc:
        warn(str(exc))
        return 1

    repo.link_dir.mkdir(parents=True, exist_ok=True)

    successfully_added = []
    for filename in filenames:
        file_path = cwd / filename
        target_path = repo.link_dir / filename
        if target_path.exists():
            warn(f"File {filename} already exists in central repo at {target_path}")
            continue
        target_path.parent.mkdir(parents=True, exist_ok=True)
        print(f"Moving {file_path} -> {target_path}")
        shutil.move(str(file_path), str(target_path))
        print(f"Creating symlink {file_path} -> {target_path}")
        file_path.symlink_to(target_path)
        successfully_added.append(filename)
        success(f"Successfully added {filename} to central repo and created symlink")

    if successfully_added:
        repo.update_gitignore(cwd, successfully_added)

    return 0
