package completion

import "strings"

// GenerateBash returns a bash completion script for ewasd. It calls
// `ewasd __complete` for every decision and only handles bash-specific
// plumbing: turning COMP_WORDS into a call, splitting the "__ewasd_dirs__"
// marker out into a native `compgen -d` directory completion, and feeding
// the rest to `compgen -W`.
func GenerateBash() string {
	return `# bash completion for ewasd
# ewasd commands: ` + strings.Join(Verbs, " ") + `
#
# Generated by "ewasd completion bash". Install with:
#   ewasd completion bash --install
# or source it directly in your shell startup:
#   source <(ewasd completion bash)
#
# All completion decisions are delegated to "ewasd __complete"; this
# function only adapts its output to bash's completion machinery.
_ewasd_complete() {
    local cur raw line dirs
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    raw="$(ewasd __complete "${COMP_WORDS[@]:1:COMP_CWORD}" 2>/dev/null)"
    dirs=0
    local -a candidates=()
    while IFS= read -r line; do
        [[ -z "$line" ]] && continue
        if [[ "$line" == "__ewasd_dirs__" ]]; then
            dirs=1
        else
            candidates+=("$line")
        fi
    done <<< "$raw"
    if [[ $dirs -eq 1 ]]; then
        COMPREPLY+=($(compgen -d -- "$cur"))
    fi
    if [[ ${#candidates[@]} -gt 0 ]]; then
        COMPREPLY+=($(compgen -W "${candidates[*]}" -- "$cur"))
    fi
    return 0
}
complete -F _ewasd_complete ewasd
`
}

// GenerateFish returns a fish completion script for ewasd, following the
// same thin-wrapper design as GenerateBash.
func GenerateFish() string {
	return `# fish completion for ewasd
# ewasd commands: ` + strings.Join(Verbs, " ") + `
#
# Generated by "ewasd completion fish". Install with:
#   ewasd completion fish --install
# or copy the output to ~/.config/fish/completions/ewasd.fish
#
# All completion decisions are delegated to "ewasd __complete"; this
# function only adapts its output to fish's completion machinery.
function __ewasd_complete
    set -l cur (commandline -ct)
    set -l prior (commandline -opc)
    set -l args $prior[2..-1] $cur
    set -l raw (ewasd __complete $args 2>/dev/null)
    set -l dirs 0
    set -l candidates
    for line in $raw
        if test "$line" = "__ewasd_dirs__"
            set dirs 1
        else
            set candidates $candidates $line
        end
    end
    if test $dirs -eq 1
        __fish_complete_directories $cur
    end
    for c in $candidates
        echo $c
    end
end

complete -c ewasd -f -a '(__ewasd_complete)'
`
}

// GenerateZsh returns a zsh completion script for ewasd, following the
// same thin-wrapper design as GenerateBash.
func GenerateZsh() string {
	return `#compdef ewasd
# zsh completion for ewasd
# ewasd commands: ` + strings.Join(Verbs, " ") + `
#
# Generated by "ewasd completion zsh". Install with:
#   ewasd completion zsh --install
# (make sure the install directory is on your $fpath before compinit runs)
#
# All completion decisions are delegated to "ewasd __complete"; this
# function only adapts its output to zsh's completion machinery.
_ewasd() {
    local -a raw candidates
    local line dirs
    dirs=0
    if (( CURRENT >= 2 )); then
        raw=(${(f)"$(ewasd __complete ${words[2,CURRENT]} 2>/dev/null)"})
    fi
    candidates=()
    for line in "${raw[@]}"; do
        [[ -z "$line" ]] && continue
        if [[ "$line" == "__ewasd_dirs__" ]]; then
            dirs=1
        else
            candidates+=("$line")
        fi
    done
    if (( dirs )); then
        _path_files -/
    fi
    if (( ${#candidates[@]} )); then
        compadd -a candidates
    fi
}
_ewasd "$@"
`
}
