package legacy

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/dmitrii-galantsev/ewasd/internal/domain"
	"github.com/dmitrii-galantsev/ewasd/internal/fsops"
	"github.com/dmitrii-galantsev/ewasd/internal/gitutil"
)

func TestDiscoverUsesExactLegacySymlinksAndReportsStaleEntries(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	workspace := filepath.Join(root, "legacy")
	source := filepath.Join(workspace, "repos", "demo")
	repository := filepath.Join(root, "repository")
	if err := os.MkdirAll(source, 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.Mkdir(repository, 0o755); err != nil {
		t.Fatal(err)
	}
	runGit(t, repository, "init", "-q")
	runGit(t, repository, "remote", "add", "origin", "git@github.com:example/demo.git")
	if err := os.WriteFile(filepath.Join(workspace, "editors.toml"), []byte("[repos.demo]\nrepo = \"https://github.com/example/demo.git\"\nlink_dir = \"repos/demo\"\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(source, "AGENT.md"), []byte("legacy"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(filepath.Join(source, "AGENT.md"), filepath.Join(repository, "AGENT.md")); err != nil {
		t.Fatal(err)
	}
	marker := filepath.Join(repository, markerName)
	if err := os.WriteFile(marker, []byte("# Auto-generated by ewasd\n# Editor configuration files\n.ewasd_gitignore\nAGENT.md\nstale.md\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	plan, err := Discover(workspace, []string{root})
	if err != nil {
		t.Fatal(err)
	}
	if len(plan.Projects) != 1 || plan.Projects[0].Name != "demo" || plan.Projects[0].Root != repository || len(plan.Projects[0].Entries) != 1 {
		t.Fatalf("unexpected project discovery: %+v", plan)
	}
	entry := plan.Projects[0].Entries[0]
	if entry.Path != "AGENT.md" || entry.LegacySource != filepath.Join(source, "AGENT.md") {
		t.Fatalf("unexpected entry: %+v", entry)
	}
	if len(plan.Skipped) != 1 || plan.Skipped[0].Blocking || plan.Skipped[0].Path != "stale.md" {
		t.Fatalf("stale entry was not reported correctly: %+v", plan.Skipped)
	}
}

func TestFinalizeMarkerArchivesAndUnsetsOnlyMatchingExclude(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	legacy := filepath.Join(root, "legacy")
	repository := filepath.Join(root, "repository")
	dataRoot := filepath.Join(root, "new")
	if err := os.MkdirAll(legacy, 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.Mkdir(repository, 0o755); err != nil {
		t.Fatal(err)
	}
	runGit(t, repository, "init", "-q")
	newSource := filepath.Join(dataRoot, "profiles", "demo", "files", "AGENT.md")
	if err := os.MkdirAll(filepath.Dir(newSource), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(newSource, []byte("new"), 0o600); err != nil {
		t.Fatal(err)
	}
	target := filepath.Join(repository, "AGENT.md")
	if err := os.Symlink(newSource, target); err != nil {
		t.Fatal(err)
	}
	marker := filepath.Join(repository, markerName)
	content := []byte("# Auto-generated by ewasd\n# Editor configuration files\n.ewasd_gitignore\nAGENT.md\n")
	if err := os.WriteFile(marker, content, 0o600); err != nil {
		t.Fatal(err)
	}
	runGit(t, repository, "config", "core.excludesFile", marker)
	archive, err := FinalizeMarker(domainMarker(marker, repository, "AGENT.md"), legacy, dataRoot)
	if err != nil {
		t.Fatal(err)
	}
	if data, err := os.ReadFile(archive); err != nil || string(data) != string(content) {
		t.Fatalf("marker archive mismatch: %q, %v", data, err)
	}
	if _, err := os.Stat(marker); !os.IsNotExist(err) {
		t.Fatalf("marker remains: %v", err)
	}
	command := exec.Command("git", "config", "--get", "core.excludesFile")
	command.Dir = repository
	if output, err := command.Output(); err == nil && filepath.Clean(strings.TrimSpace(string(output))) == filepath.Clean(marker) {
		t.Fatal("legacy core.excludesFile was not unset")
	}
	if !fsops.LinkPointsTo(target, newSource) {
		t.Fatal("finalization changed the migrated link")
	}
}

func TestFinalizeMarkersGroupsSharedWorktreeConfigAndPreservesResidualIgnores(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	legacy := filepath.Join(root, "legacy")
	mainRepo := filepath.Join(root, "main")
	worktree := filepath.Join(root, "worktree")
	dataRoot := filepath.Join(root, "state")
	if err := os.MkdirAll(legacy, 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.Mkdir(mainRepo, 0o755); err != nil {
		t.Fatal(err)
	}
	runGit(t, mainRepo, "init", "-q")
	runGit(t, mainRepo, "config", "user.email", "test@example.com")
	runGit(t, mainRepo, "config", "user.name", "Test")
	if err := os.WriteFile(filepath.Join(mainRepo, "tracked"), []byte("x"), 0o600); err != nil {
		t.Fatal(err)
	}
	runGit(t, mainRepo, "add", "tracked")
	runGit(t, mainRepo, "commit", "-qm", "fixture")
	runGit(t, mainRepo, "worktree", "add", "-q", "-b", "other", worktree)
	newSource := filepath.Join(dataRoot, "profiles", "shared", "files", "AGENT.md")
	if err := os.MkdirAll(filepath.Dir(newSource), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(newSource, []byte("shared"), 0o600); err != nil {
		t.Fatal(err)
	}
	markers := []domain.LegacyMarkerPlan{}
	for _, checkout := range []string{mainRepo, worktree} {
		if err := os.Symlink(newSource, filepath.Join(checkout, "AGENT.md")); err != nil {
			t.Fatal(err)
		}
		marker := filepath.Join(checkout, markerName)
		content := "# Auto-generated by ewasd\n# Editor configuration files\n.ewasd_gitignore\nAGENT.md\nstale-local.md\n"
		if err := os.WriteFile(marker, []byte(content), 0o600); err != nil {
			t.Fatal(err)
		}
		markers = append(markers, domain.LegacyMarkerPlan{Path: marker, GitRoot: checkout, Entries: []string{"AGENT.md"}, Residual: []string{"stale-local.md"}})
	}
	runGit(t, mainRepo, "config", "core.excludesFile", filepath.Join(mainRepo, markerName))
	archives, err := FinalizeMarkers(markers, legacy, dataRoot)
	if err != nil || len(archives) != 2 {
		t.Fatalf("finalize shared worktrees: %v, %v", archives, err)
	}
	if err := ResumeFinalization(dataRoot); err != nil {
		t.Fatalf("completed finalization was not idempotent: %v", err)
	}
	for _, checkout := range []string{mainRepo, worktree} {
		if _, err := os.Stat(filepath.Join(checkout, markerName)); !os.IsNotExist(err) {
			t.Fatalf("marker remains in %s: %v", checkout, err)
		}
		check := exec.Command("git", "check-ignore", "--no-index", "-q", "--", "stale-local.md")
		check.Dir = checkout
		if err := check.Run(); err != nil {
			t.Fatalf("residual ignore was not preserved in %s: %v", checkout, err)
		}
	}
	origin := exec.Command("git", "config", "--local", "--get", "core.excludesFile")
	origin.Dir = mainRepo
	if err := origin.Run(); err == nil {
		t.Fatal("shared repository core.excludesFile remains configured")
	}
}

func TestDiscoverSkipsForeignMarkerWithoutAborting(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	workspace := filepath.Join(root, "legacy")
	source := filepath.Join(workspace, "repos", "demo")
	repository := filepath.Join(root, "repository")
	foreign := filepath.Join(root, "foreign")
	for _, directory := range []string{source, repository, foreign} {
		if err := os.MkdirAll(directory, 0o700); err != nil {
			t.Fatal(err)
		}
	}
	runGit(t, repository, "init", "-q")
	if err := os.WriteFile(filepath.Join(workspace, "editors.toml"), []byte("[repos.demo]\nrepo = \"https://example/demo\"\nlink_dir = \"repos/demo\"\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(foreign, markerName), []byte("hand written\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	plan, err := Discover(workspace, []string{root})
	if err != nil {
		t.Fatal(err)
	}
	if len(plan.Skipped) != 1 || plan.Skipped[0].Blocking || plan.Skipped[0].Reason != ErrNotGeneratedMarker.Error() {
		t.Fatalf("foreign marker was not safely skipped: %+v", plan.Skipped)
	}
}

func TestResumeFinalizationConvergesAfterSideEffectsBeforeJournalUpdate(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	legacy := filepath.Join(root, "legacy")
	repository := filepath.Join(root, "repository")
	dataRoot := filepath.Join(root, "state")
	if err := os.MkdirAll(legacy, 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.Mkdir(repository, 0o755); err != nil {
		t.Fatal(err)
	}
	runGit(t, repository, "init", "-q")
	newSource := filepath.Join(dataRoot, "profiles", "demo", "files", "AGENT.md")
	if err := os.MkdirAll(filepath.Dir(newSource), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(newSource, []byte("new"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(newSource, filepath.Join(repository, "AGENT.md")); err != nil {
		t.Fatal(err)
	}
	markerPath := filepath.Join(repository, markerName)
	if err := os.WriteFile(markerPath, []byte("# Auto-generated by ewasd\n.ewasd_gitignore\nAGENT.md\nstale.md\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	runGit(t, repository, "config", "core.excludesFile", markerPath)
	marker := domain.LegacyMarkerPlan{Path: markerPath, GitRoot: repository, Entries: []string{"AGENT.md"}, Residual: []string{"stale.md"}}
	if err := prepareFinalization([]domain.LegacyMarkerPlan{marker}, legacy, dataRoot); err != nil {
		t.Fatal(err)
	}
	state, err := readFinalization(dataRoot)
	if err != nil || len(state.Configs) != 1 {
		t.Fatalf("prepared finalization: %+v, %v", state, err)
	}
	// Perform every side effect but deliberately do not update finalization.json,
	// exactly modeling a process death between syscall and journal write.
	if err := gitutil.UpdateLegacyResidual(markerArchiveKey(markerPath), repository, marker.Residual); err != nil {
		t.Fatal(err)
	}
	if err := unsetFinalizationConfig(state.Configs[0]); err != nil {
		t.Fatal(err)
	}
	if err := os.Remove(markerPath); err != nil {
		t.Fatal(err)
	}
	if err := ResumeFinalization(dataRoot); err != nil {
		t.Fatal(err)
	}
	finished, err := readFinalization(dataRoot)
	if err != nil || !finished.Completed || !finished.Markers[0].Removed || !finished.Configs[0].Unset {
		t.Fatalf("finalization did not converge: %+v, %v", finished, err)
	}
}

func TestCompletedFinalizationAcceptsANewMarkerBatch(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	legacy := filepath.Join(root, "legacy")
	dataRoot := filepath.Join(root, "state")
	if err := os.MkdirAll(legacy, 0o700); err != nil {
		t.Fatal(err)
	}
	makeMarker := func(name string) domain.LegacyMarkerPlan {
		repository := filepath.Join(root, name)
		if err := os.Mkdir(repository, 0o755); err != nil {
			t.Fatal(err)
		}
		runGit(t, repository, "init", "-q")
		marker := filepath.Join(repository, markerName)
		if err := os.WriteFile(marker, []byte("# Auto-generated by ewasd\n.ewasd_gitignore\n"), 0o600); err != nil {
			t.Fatal(err)
		}
		return domain.LegacyMarkerPlan{Path: marker, GitRoot: repository}
	}
	first := makeMarker("first")
	if _, err := FinalizeMarkers([]domain.LegacyMarkerPlan{first}, legacy, dataRoot); err != nil {
		t.Fatal(err)
	}
	second := makeMarker("second")
	if _, err := FinalizeMarkers([]domain.LegacyMarkerPlan{second}, legacy, dataRoot); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(second.Path); !os.IsNotExist(err) {
		t.Fatalf("second-wave marker remains: %v", err)
	}
	history, err := filepath.Glob(filepath.Join(dataRoot, "legacy", "finalization-history-*.json"))
	if err != nil || len(history) != 1 {
		t.Fatalf("completed finalization was not archived: %v, %v", history, err)
	}
}

func domainMarker(path, gitRoot string, entries ...string) domain.LegacyMarkerPlan {
	return domain.LegacyMarkerPlan{Path: path, GitRoot: gitRoot, Entries: entries}
}

func runGit(t *testing.T, cwd string, args ...string) {
	t.Helper()
	command := exec.Command("git", args...)
	command.Dir = cwd
	if output, err := command.CombinedOutput(); err != nil {
		t.Fatalf("git %v: %v: %s", args, err, output)
	}
}
